model:
  base_learning_rate: 4.5e-6
  target: taming_comb.models.vqgan.VQModelCrossGAN_ADAIN
  params:
    embed_dim: 512
    n_embed: 512
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming_comb.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0 #301
        disc_factor: 1.0 #0.8 / 0.3
        disc_weight: 0.1 # 0.5 / 0.8
        codebook_weight: 1.0